[package]
name = "justpic-storage"
version = "0.1.0"
edition.workspace = true
description = "Justpic files storage package"

[dependencies]
# Futures
async-trait = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "fs", "io-util"] }
tokio-util = { workspace = true }

# Utils
rand = { workspace = true }
uuid = { workspace = true, features = ["v4"] }
derive_more = { workspace = true, features = ["from", "display"] }

[lints]
workspace = true