[package]
name = "justpic-database"
version = "0.1.0"
edition.workspace = true
description = "Justpic database package"

[dependencies]
# Futures
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "fs", "io-util"] }
tokio-util = { workspace = true }

# Database
sqlx = { workspace = true, features = ["runtime-tokio", "sqlite", "migrate"] }

# Utils
derive_more = { workspace = true, features = ["from", "display"] }

[lints]
workspace = true